# Generated by Django 5.0.6 on 2024-06-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('screen', '0002_remove_catalog_vendor_catalog_vender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
