# Generated by Django 5.0.6 on 2024-06-26 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='area name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='area description')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='area location')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='category description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ScreenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='screen type name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='screen type description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'screen type',
                'verbose_name_plural': 'screen types',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='TShirtSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='t-shirt size name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='t-shirt size description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 't-shirt size',
                'verbose_name_plural': 't-shirt sizes',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject')),
                ('message', models.TextField(blank=True, null=True, verbose_name='message')),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('vender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.vendor')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='subcategory name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='subcategory description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.category')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategories',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='reference id')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
                ('marketing_description', models.TextField(max_length=500, verbose_name='marketing description')),
                ('size', models.CharField(max_length=20, verbose_name='size')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('landmark', models.CharField(max_length=200, verbose_name='landmark')),
                ('avg_monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='average monthly price')),
                ('hide_price_to_buyer', models.BooleanField(default=False, verbose_name='hide price to buyer')),
                ('gps_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='gps latitude')),
                ('gps_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='gps longitude')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='thumbnail')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='available from')),
                ('available_to', models.DateField(blank=True, null=True, verbose_name='available to')),
                ('visibility', models.CharField(blank=True, max_length=50, null=True)),
                ('illumination', models.CharField(blank=True, max_length=50, null=True)),
                ('benefits_and_cta', models.CharField(blank=True, max_length=200, null=True)),
                ('average_weekly_impressions', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.area')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.category')),
                ('screen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.screentype')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='screen.subcategory')),
                ('tshirt_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.tshirtsize')),
            ],
            options={
                'verbose_name': 'catalog',
                'verbose_name_plural': 'catalogs',
            },
        ),
    ]
